# Copyright 2001-2016 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	suppress_vs_warnings = ['/W0']
	if bld.env['MSVC_VERSION'] == '14.0':
		suppress_vs_warnings = [ '/W0', '/Wv:18' ]

	bld.CryEngineStaticModule( 
		target    = 'oculus', 
		vs_filter = 'Libs',
		file_list = 'oculus.waf_files',
		exclude_from_static_code_analyzer = True,

		win_cxxflags = [ '/FI' + bld.CreateRootRelativePath('Code/Libs/Oculus/PatchOculusSDK.h') ] + suppress_vs_warnings,
		win_cflags = [ '/FI' + bld.CreateRootRelativePath('Code/Libs/Oculus/PatchOculusSDK.h') ] + suppress_vs_warnings,
		includes    = [
			Path('Code/SDKs/OculusSDK/LibOVR/Include'),
			Path('Code/SDKs/OculusSDK/LibOVRKernel/Src'),
			],

		win_lib = ['OleAut32'],

		module_provides = dict(
			includes = [ Path('Code/SDKs/OculusSDK/LibOVR/Include'), ],
			defines  = [ 'INCLUDE_OCULUS_SDK' ],
		),
	)
